"use client";

import React, { useMemo } from "react";
import type { AIStructure } from "./aiStructure";

/* ======================================================
   PROPS
====================================================== */

type Props = {
  username: string;
  structure: AIStructure;
  content: any;
  editMode: boolean;
};

/* ======================================================
   UTILS
====================================================== */

function cx(...classes: (string | false | undefined | null)[]) {
  return classes.filter(Boolean).join(" ");
}

function str(v: any, fallback = ""): string {
  if (v === null || v === undefined) return fallback;
  const s = String(v);
  return s.trim().length ? s : fallback;
}

function asArray<T = any>(v: any): T[] {
  return Array.isArray(v) ? v : [];
}

/**
 * Content normalization layer
 * Supports:
 * 1) New nested content_json:
 *    content.hero.headline, content.services.items, content.process.steps, etc.
 * 2) Old/flat AI content:
 *    content.hero_headline, content.services[], content.process[], etc.
 */
function normalizeContent(raw: any, username: string) {
  const c = raw || {};

  // HERO
  const heroHeadline =
    str(c?.hero?.headline) || str(c?.hero_headline) || str(username, "Your Website");

  const heroSubheadline =
    str(c?.hero?.subheadline) || str(c?.hero_subheadline) || "Generated by AutopilotAI.";

  const heroImage = c?.hero?.image ?? c?.hero_image ?? null;

  const ctaText =
    str(c?.hero?.cta_text) ||
    str(c?.cta_text) ||
    str(c?.cta?.text) ||
    "Get started";

  const ctaLink =
    str(c?.hero?.cta_link) ||
    str(c?.cta_link) ||
    str(c?.cta?.link) ||
    "#contact";

  // TRUST
  const trustItems =
    asArray(c?.trust?.items).length > 0
      ? asArray(c?.trust?.items)
      : asArray(c?.trust);

  // ABOUT
  const aboutTitle =
    str(c?.about?.title) || str(c?.about_title) || "About";

  const aboutText =
    str(c?.about?.text) || str(c?.about_text) || "";

  const aboutImage = c?.about?.image ?? c?.about_image ?? null;

  // SERVICES
  const servicesTitle =
    str(c?.services?.title) || str(c?.services_title) || "Services";

  const servicesSubtitle =
    str(c?.services?.subtitle) || str(c?.services_subtitle) || "";

  const servicesItems =
    asArray(c?.services?.items).length > 0
      ? asArray(c?.services?.items)
      : asArray(c?.services);

  // PROCESS
  const processTitle =
    str(c?.process?.title) || str(c?.process_title) || "How it works";

  const processSteps =
    asArray(c?.process?.steps).length > 0
      ? asArray(c?.process?.steps)
      : asArray(c?.process);

  // TESTIMONIAL
  const testimonialEnabled =
    typeof c?.testimonial?.enabled === "boolean" ? c.testimonial.enabled : true;

  const testimonialQuote =
    str(c?.testimonial?.quote) || str(c?.testimonial_quote) || "";

  const testimonialName =
    str(c?.testimonial?.name) || str(c?.testimonial_name) || "Customer";

  const testimonialRole =
    str(c?.testimonial?.role) || str(c?.testimonial_role) || "";

  // CTA SECTION (separate section)
  const ctaHeadline =
    str(c?.cta?.headline) || str(c?.cta_headline) || "Ready to take the next step?";

  const ctaSectionText =
    str(c?.cta?.text) || str(c?.cta_text) || ctaText;

  return {
    hero: {
      headline: heroHeadline,
      subheadline: heroSubheadline,
      image: heroImage,
      cta_text: ctaText,
      cta_link: ctaLink,
    },
    trust: {
      items: trustItems.map((t: any) => ({
        label: str(t?.label, "Metric"),
        value: str(t?.value, "—"),
      })),
    },
    about: {
      title: aboutTitle,
      text: aboutText,
      image: aboutImage,
    },
    services: {
      title: servicesTitle,
      subtitle: servicesSubtitle,
      items: servicesItems.map((s: any) => ({
        title: str(s?.title, "Service"),
        description: str(s?.description, ""),
        icon: s?.icon ? str(s.icon) : undefined,
      })),
    },
    process: {
      title: processTitle,
      steps: processSteps.map((p: any) => ({
        title: str(p?.title, "Step"),
        description: str(p?.description, ""),
      })),
    },
    testimonial: {
      enabled: testimonialEnabled,
      quote: testimonialQuote,
      name: testimonialName,
      role: testimonialRole,
    },
    cta: {
      headline: ctaHeadline,
      text: ctaSectionText,
      link: ctaLink,
    },
  };
}

/* ======================================================
   THEME TOKENS (AI FEEL)
====================================================== */

function useThemeTokens(structure: AIStructure) {
  const isDark = structure.theme.palette === "dark";
  const accent = structure.theme.accent || "indigo";

  // Keep it deterministic: map accent -> classes
  const accentMap: Record<
    string,
    { glow: string; chip: string; btn: string; ring: string }
  > = {
    indigo: {
      glow: "from-indigo-500/25 via-purple-500/15 to-transparent",
      chip: "bg-indigo-500/10 text-indigo-200 border-indigo-500/20",
      btn: "bg-indigo-500 text-white hover:bg-indigo-400",
      ring: "focus:ring-indigo-500/25",
    },
    emerald: {
      glow: "from-emerald-500/20 via-teal-500/10 to-transparent",
      chip: "bg-emerald-500/10 text-emerald-200 border-emerald-500/20",
      btn: "bg-emerald-500 text-black hover:bg-emerald-400",
      ring: "focus:ring-emerald-500/25",
    },
    orange: {
      glow: "from-orange-500/20 via-amber-500/10 to-transparent",
      chip: "bg-orange-500/10 text-orange-200 border-orange-500/20",
      btn: "bg-orange-500 text-black hover:bg-orange-400",
      ring: "focus:ring-orange-500/25",
    },
    neutral: {
      glow: "from-slate-500/18 via-zinc-500/10 to-transparent",
      chip: "bg-white/5 text-white/80 border-white/12",
      btn: "bg-white text-black hover:bg-gray-100",
      ring: "focus:ring-white/25",
    },
  };

  const a = accentMap[accent] || accentMap.indigo;

  return {
    isDark,
    accent,
    glow: a.glow,
    chip: a.chip,
    btn: a.btn,
    ring: a.ring,
    pageBg: isDark ? "bg-[#05070d] text-white" : "bg-[#f6f7fb] text-black",
    panel: isDark
      ? "bg-white/5 border-white/10"
      : "bg-white/70 border-black/10 backdrop-blur",
    softText: isDark ? "text-white/60" : "text-black/60",
    strongText: isDark ? "text-white" : "text-black",
    divider: isDark ? "bg-white/10" : "bg-black/10",
  };
}

/* ======================================================
   HERO VARIANTS (NOW USES NORMALIZED CONTENT)
====================================================== */

function Hero({
  variant,
  c,
  t,
}: {
  variant: AIStructure["hero"]["variant"];
  c: ReturnType<typeof normalizeContent>;
  t: ReturnType<typeof useThemeTokens>;
}) {
  const headline = c.hero.headline;
  const sub = c.hero.subheadline;

  const PrimaryCTA = (
    <a
      href={c.hero.cta_link || "#contact"}
      className={cx(
        "inline-flex items-center justify-center rounded-xl px-6 py-3 text-sm font-semibold transition",
        t.isDark
          ? cx("shadow-[0_40px_120px_rgba(0,0,0,.55)]", t.btn)
          : "bg-black text-white hover:bg-black/90",
        "focus:outline-none focus:ring-2",
        t.ring
      )}
    >
      {c.hero.cta_text || "Get started"}
      <span className="ml-2 opacity-80">→</span>
    </a>
  );

  const SecondaryCTA = (
    <a
      href="#contact"
      className={cx(
        "inline-flex items-center justify-center rounded-xl px-6 py-3 text-sm font-semibold transition border",
        t.isDark
          ? "border-white/15 bg-white/5 hover:bg-white/10 text-white"
          : "border-black/10 bg-black/5 hover:bg-black/10 text-black"
      )}
    >
      Contact
    </a>
  );

  switch (variant) {
    case "minimal":
      return (
        <section className="pt-24 pb-16 px-6">
          <div className="max-w-6xl mx-auto text-center">
            <div
              className={cx(
                "inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs",
                t.chip
              )}
            >
              <span className="opacity-90">AutopilotAI</span>
              <span className="opacity-60">•</span>
              <span className="opacity-90">Generated</span>
            </div>
            <h1
              className={cx(
                "mt-6 text-4xl md:text-6xl font-semibold tracking-tight",
                t.strongText
              )}
            >
              {headline}
            </h1>
          </div>
        </section>
      );

    case "image_background":
      return (
        <section className="relative pt-24 pb-20 px-6 overflow-hidden">
          <div
            className={cx(
              "absolute -inset-12 blur-3xl opacity-70 bg-gradient-to-r",
              t.glow
            )}
          />
          {c.hero.image && (
            <img
              src={c.hero.image}
              alt=""
              className="absolute inset-0 w-full h-full object-cover opacity-30"
            />
          )}
          <div
            className={cx(
              "absolute inset-0",
              t.isDark ? "bg-black/55" : "bg-white/70"
            )}
          />
          <div className="relative max-w-6xl mx-auto text-center">
            <div
              className={cx(
                "inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs",
                t.chip
              )}
            >
              AI layout • theme • copy
            </div>
            <h1
              className={cx(
                "mt-6 text-4xl md:text-6xl font-semibold tracking-tight",
                t.strongText
              )}
            >
              {headline}
            </h1>
            <p
              className={cx(
                "mt-5 text-lg md:text-xl max-w-3xl mx-auto",
                t.softText
              )}
            >
              {sub}
            </p>
            <div className="mt-8 flex flex-col sm:flex-row gap-3 justify-center">
              {PrimaryCTA}
              {SecondaryCTA}
            </div>
          </div>
        </section>
      );

    case "centered_text":
      return (
        <section className="pt-24 pb-16 px-6">
          <div className="max-w-6xl mx-auto text-center">
            <div
              className={cx(
                "inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs",
                t.chip
              )}
            >
              AI-generated website
            </div>
            <h1
              className={cx(
                "mt-6 text-4xl md:text-6xl font-semibold tracking-tight",
                t.strongText
              )}
            >
              {headline}
            </h1>
            <p
              className={cx(
                "mt-5 text-lg md:text-xl max-w-3xl mx-auto",
                t.softText
              )}
            >
              {sub}
            </p>
            <div className="mt-8 flex flex-col sm:flex-row gap-3 justify-center">
              {PrimaryCTA}
              {SecondaryCTA}
            </div>
          </div>
        </section>
      );

    case "split_image":
    default:
      return (
        <section className="pt-24 pb-16 px-6">
          <div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-10 items-center">
            <div>
              <div
                className={cx(
                  "inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs",
                  t.chip
                )}
              >
                AutopilotAI • Generated
              </div>
              <h1
                className={cx(
                  "mt-6 text-4xl md:text-6xl font-semibold tracking-tight",
                  t.strongText
                )}
              >
                {headline}
              </h1>
              <p className={cx("mt-5 text-lg md:text-xl", t.softText)}>{sub}</p>
              <div className="mt-8 flex flex-col sm:flex-row gap-3">
                {PrimaryCTA}
                {SecondaryCTA}
              </div>
            </div>

            <div className={cx("rounded-3xl border overflow-hidden", t.panel)}>
              <div
                className={cx(
                  "relative aspect-[4/3] w-full",
                  t.isDark ? "bg-black/40" : "bg-white"
                )}
              >
                {c.hero.image ? (
                  <img src={c.hero.image} alt="" className="w-full h-full object-cover" />
                ) : (
                  <div className="w-full h-full flex items-center justify-center">
                    <div className={cx("text-center px-8", t.softText)}>
                      <div className="font-semibold">Hero image</div>
                      <div className="text-xs mt-2 opacity-80">No image set</div>
                    </div>
                  </div>
                )}
                <div
                  className={cx(
                    "absolute -inset-10 blur-3xl opacity-60 bg-gradient-to-r",
                    t.glow
                  )}
                />
              </div>
            </div>
          </div>
        </section>
      );
  }
}

/* ======================================================
   SECTIONS (NOW USE NORMALIZED CONTENT)
====================================================== */

function SectionShell({
  children,
  t,
  subtle,
}: {
  children: React.ReactNode;
  t: ReturnType<typeof useThemeTokens>;
  subtle?: boolean;
}) {
  return (
    <section
      className={cx(
        "px-6 py-16",
        subtle ? (t.isDark ? "bg-white/[0.03]" : "bg-black/[0.02]") : ""
      )}
    >
      <div className="max-w-6xl mx-auto">{children}</div>
    </section>
  );
}

function Trust({ c, t }: { c: ReturnType<typeof normalizeContent>; t: ReturnType<typeof useThemeTokens> }) {
  if (!c.trust.items.length) return null;

  return (
    <SectionShell t={t}>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {c.trust.items.map((it, i) => (
          <div key={i} className={cx("rounded-2xl border p-5", t.panel)}>
            <div className={cx("text-2xl font-semibold", t.strongText)}>{it.value}</div>
            <div className={cx("mt-1 text-sm", t.softText)}>{it.label}</div>
          </div>
        ))}
      </div>
    </SectionShell>
  );
}

function About({ c, t }: { c: ReturnType<typeof normalizeContent>; t: ReturnType<typeof useThemeTokens> }) {
  if (!str(c.about.text)) return null;

  return (
    <SectionShell t={t} subtle>
      <div className="grid md:grid-cols-2 gap-10 items-start">
        <div>
          <div className={cx("text-xs uppercase tracking-wide", t.softText)}>About</div>
          <h2 className={cx("mt-2 text-3xl md:text-4xl font-semibold", t.strongText)}>
            {c.about.title}
          </h2>
          <p className={cx("mt-5 leading-relaxed whitespace-pre-line", t.softText)}>
            {c.about.text}
          </p>
        </div>

        <div className={cx("rounded-3xl border overflow-hidden", t.panel)}>
          <div className="aspect-[4/3] w-full">
            {c.about.image ? (
              <img src={c.about.image} alt="" className="w-full h-full object-cover" />
            ) : (
              <div className="w-full h-full flex items-center justify-center">
                <div className={cx("text-center px-8", t.softText)}>
                  <div className="font-semibold">About image</div>
                  <div className="text-xs mt-2 opacity-80">No image set</div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </SectionShell>
  );
}

function Services({ c, t }: { c: ReturnType<typeof normalizeContent>; t: ReturnType<typeof useThemeTokens> }) {
  if (!c.services.items.length) return null;

  return (
    <SectionShell t={t}>
      <div className="flex items-end justify-between gap-6 flex-wrap">
        <div>
          <div className={cx("text-xs uppercase tracking-wide", t.softText)}>Services</div>
          <h2 className={cx("mt-2 text-3xl md:text-4xl font-semibold", t.strongText)}>
            {c.services.title}
          </h2>
          {c.services.subtitle && <p className={cx("mt-3", t.softText)}>{c.services.subtitle}</p>}
        </div>
      </div>

      <div className="mt-10 grid md:grid-cols-2 lg:grid-cols-3 gap-5">
        {c.services.items.map((s, i) => (
          <div key={i} className={cx("rounded-2xl border p-6", t.panel)}>
            <div className={cx("text-lg font-semibold", t.strongText)}>{s.title}</div>
            {s.description && (
              <div className={cx("mt-2 text-sm leading-relaxed", t.softText)}>{s.description}</div>
            )}
          </div>
        ))}
      </div>
    </SectionShell>
  );
}

function Process({ c, t }: { c: ReturnType<typeof normalizeContent>; t: ReturnType<typeof useThemeTokens> }) {
  if (!c.process.steps.length) return null;

  return (
    <SectionShell t={t} subtle>
      <div>
        <div className={cx("text-xs uppercase tracking-wide", t.softText)}>Process</div>
        <h2 className={cx("mt-2 text-3xl md:text-4xl font-semibold", t.strongText)}>
          {c.process.title}
        </h2>
      </div>

      <div className="mt-10 grid md:grid-cols-3 gap-5">
        {c.process.steps.map((p, i) => (
          <div key={i} className={cx("rounded-2xl border p-6", t.panel)}>
            <div className={cx("text-xs font-semibold inline-flex px-3 py-1 rounded-full border", t.chip)}>
              Step {i + 1}
            </div>
            <div className={cx("mt-4 text-lg font-semibold", t.strongText)}>{p.title}</div>
            {p.description && (
              <div className={cx("mt-2 text-sm leading-relaxed", t.softText)}>{p.description}</div>
            )}
          </div>
        ))}
      </div>
    </SectionShell>
  );
}

function Testimonial({ c, t }: { c: ReturnType<typeof normalizeContent>; t: ReturnType<typeof useThemeTokens> }) {
  if (!c.testimonial.enabled) return null;
  if (!str(c.testimonial.quote)) return null;

  return (
    <SectionShell t={t}>
      <div className={cx("rounded-3xl border p-10", t.panel)}>
        <div className={cx("text-xs uppercase tracking-wide", t.softText)}>Testimonial</div>
        <div className={cx("mt-4 text-2xl md:text-3xl font-semibold leading-tight", t.strongText)}>
          “{c.testimonial.quote}”
        </div>
        <div className={cx("mt-6 text-sm", t.softText)}>
          — {c.testimonial.name}
          {c.testimonial.role ? `, ${c.testimonial.role}` : ""}
        </div>
      </div>
    </SectionShell>
  );
}

function CTA({ c, t }: { c: ReturnType<typeof normalizeContent>; t: ReturnType<typeof useThemeTokens> }) {
  const buttonLabel = str(c.cta.text) || str(c.hero.cta_text, "Get started");

  return (
    <SectionShell t={t} subtle>
      <div className={cx("rounded-3xl border p-10 md:p-12 text-center", t.panel)}>
        <h2 className={cx("text-3xl md:text-4xl font-semibold", t.strongText)}>{c.cta.headline}</h2>
        <p className={cx("mt-4 max-w-2xl mx-auto", t.softText)}>
          {str(c.cta.text, "Click below to get in touch.")}
        </p>
        <div className="mt-8 flex justify-center">
          <a
            href={c.cta.link || "#contact"}
            className={cx(
              "inline-flex items-center justify-center rounded-xl px-7 py-3.5 text-sm font-semibold transition",
              t.isDark ? t.btn : "bg-black text-white hover:bg-black/90",
              "focus:outline-none focus:ring-2",
              t.ring
            )}
          >
            {buttonLabel} <span className="ml-2 opacity-80">→</span>
          </a>
        </div>
      </div>
    </SectionShell>
  );
}

/* ======================================================
   FOOTER
====================================================== */

function Footer({ username, t }: { username: string; t: ReturnType<typeof useThemeTokens> }) {
  return (
    <footer className={cx("px-6 py-12", t.isDark ? "bg-black/20" : "bg-white/70 backdrop-blur")}>
      <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-3">
        <div className={cx("text-sm", t.softText)}>© {new Date().getFullYear()} {username}</div>
        <div className={cx("text-xs", t.softText)}>Powered by AutopilotAI Website Builder</div>
      </div>
    </footer>
  );
}

/* ======================================================
   MAIN RENDERER
====================================================== */

export default function AIWebsiteRenderer({ username, structure, content, editMode }: Props) {
  const t = useThemeTokens(structure);
  const c = useMemo(() => normalizeContent(content, username), [content, username]);

  return (
    <main className={cx("min-h-screen", t.pageBg)}>
      {/* Ambient background */}
      <div className="fixed inset-0 pointer-events-none -z-10">
        <div
          className={cx(
            "absolute inset-0 opacity-[0.12]",
            t.isDark
              ? "bg-[radial-gradient(ellipse_at_top_left,_rgba(255,255,255,0.12)_0%,_transparent_55%),radial-gradient(ellipse_at_bottom_right,_rgba(99,102,241,0.18)_0%,_transparent_55%)]"
              : "bg-[radial-gradient(ellipse_at_top_left,_rgba(0,0,0,0.08)_0%,_transparent_55%),radial-gradient(ellipse_at_bottom_right,_rgba(99,102,241,0.10)_0%,_transparent_55%)]"
          )}
        />
      </div>

      {editMode && (
        <div className="fixed top-4 right-4 z-50">
          <div
            className={cx(
              "rounded-full px-4 py-2 text-xs font-semibold border backdrop-blur",
              t.isDark ? "bg-white/10 border-white/15 text-white" : "bg-black/5 border-black/10 text-black"
            )}
          >
            Edit mode
          </div>
        </div>
      )}

      <Hero variant={structure.hero.variant} c={c} t={t} />

      {structure.sections.map((section, i) => {
        switch (section) {
          case "trust":
            return <Trust key={i} c={c} t={t} />;
          case "about":
            return <About key={i} c={c} t={t} />;
          case "services":
            return <Services key={i} c={c} t={t} />;
          case "process":
            return <Process key={i} c={c} t={t} />;
          case "testimonial":
            return <Testimonial key={i} c={c} t={t} />;
          case "cta":
            return <CTA key={i} c={c} t={t} />;
          default:
            return null;
        }
      })}

      <Footer username={username} t={t} />
    </main>
  );
}
